### ISSUE TITLE
[BUG] Fix video player size in recorded session

### ISSUE THREAD

**Issue by bhrg3se** [seknox/trasa#64] opened 2020-09-29 12:04 UTC
**Describe the bug:**

The video player size in the "recorded session" is bigger than the browser window itself. 

**Expected behavior:**

It should fit the window size.

**Scope of issue:**

- [ ] TRASA codebase
- [x] dashboard
- [ ] server
- [ ] mobile app
- [ ] browser extension
- [ ] device agent 
- [ ] website/docs

**Comment by sshahcodes** [comment] 2020-10-14 19:18
Size of the video depends on the dimension supplied to FFmpeg which is slightely wider than its height (for example in case of http session, size is 1920x1080). We use react player to show the video which presents the player in a square layout. This causes extra black space in the top and bottom of player. Fitting video to the available width of browser window will also increase height of video (since player is in a square layout) and decresing player height will also decrease the width. I guess it's better to present bigger video window than smaller.

This issue can be closed as "expected behaviour" given how video is recorded and played.

**Closed by sshahcodes** 2020-10-14 19:18 UTC
Labels: front-end, good first issue
